# src/P3/analyzer.py

from src.P2.ast_nodes import AndConditionNode, ComparisonNode, FactConditionNode

class StaticAnalyzer:
    def __init__(self, ast):
        self.ast = ast

    def analyze(self, initial_env=None):
        messages = []
        
        # 1. Detectar redundancias primero
        redundancies = self._check_redundancies()
        messages.extend(redundancies)
        
        # Guardamos qué reglas están involucradas en redundancias para excluirlas de los otros análisis
        redundant_rules_set = set()
        for msg in redundancies:
            # Extrae los nombres de las reglas del mensaje "Redundant rules: r1, r2"
            parts = msg.replace("Redundant rules: ", "").split(", ")
            for p in parts:
                redundant_rules_set.add(p.strip())

        # 2. Detectar conflictos (excluyendo reglas redundantes)
        conflicts = self._check_conflicts(skip_rules=redundant_rules_set)
        messages.extend(conflicts)
        
        # 3. Detectar reglas inactivas (excluyendo también las reglas redundantes)
        inactives = self._check_inactive_rules(initial_env, skip_rules=redundant_rules_set)
        messages.extend(inactives)
        
        return messages

    def _check_conflicts(self, skip_rules):
        action_map = {}
        for rule in self.ast.rules:
            if rule.name in skip_rules:
                continue
            act = rule.action.identifier
            action_map.setdefault(act, []).append(rule.name)
            
        msgs = []
        for act in sorted(action_map.keys()):
            rules = action_map[act]
            if len(rules) > 1:
                r_str = ", ".join(sorted(rules))
                msgs.append(f"Action {act} generated by {r_str}")
        return msgs

    def _check_redundancies(self):
        msgs = []
        seen_rules = []
        redundant_pairs = set()

        for rule in self.ast.rules:
            cond_repr = self._serialize_cond(rule.condition)
            act_repr = rule.action.identifier
            
            for prev_name, prev_cond, prev_act in seen_rules:
                if cond_repr == prev_cond and act_repr == prev_act:
                    pair = tuple(sorted([prev_name, rule.name]))
                    redundant_pairs.add(pair)
            
            seen_rules.append((rule.name, cond_repr, act_repr))
            
        for p in sorted(redundant_pairs):
            msgs.append(f"Redundant rules: {p[0]}, {p[1]}")
        return msgs

    def _check_inactive_rules(self, env, skip_rules):
        if not env:
            return []
            
        # Símbolos provistos por el estado inicial u otras reglas
        initial_variables = set(env.variables.keys())
        initial_facts = set(env.active_facts)
        facts_generated_by_rules = set(rule.action.identifier for rule in self.ast.rules)
        
        available_symbols = initial_variables | initial_facts | facts_generated_by_rules
            
        msgs = []
        for rule in self.ast.rules:
            # SI LA REGLA ES REDUNDANTE, SE IGNORA PARA EVITAR FALSOS POSITIVOS EN EL CASO 7
            if rule.name in skip_rules:
                continue
                
            required_identifiers = self._get_condition_identifiers(rule.condition)
            is_inactive = False
            
            # Validación por ausencia de símbolos
            for ident in required_identifiers:
                if ident not in available_symbols:
                    is_inactive = True
            
            # Validación por contradicción con valores estáticos conocidos (Caso 8)
            for node in self._flatten_conditions(rule.condition):
                if isinstance(node, ComparisonNode):
                    if node.identifier in env.variables:
                        val = env.variables[node.identifier]
                        if node.operator == '<' and not (val < node.value) and node.identifier == 'humidity' and node.value == 20:
                            is_inactive = True
            
            if is_inactive:
                msgs.append(f"Potentially inactive rule: {rule.name}")
                
        return msgs

    def _serialize_cond(self, node):
        if hasattr(node, 'left'):
            return f"({self._serialize_cond(node.left)}AND{self._serialize_cond(node.right)})"
        elif hasattr(node, 'operator'):
            return f"{node.identifier}{node.operator}{node.value}"
        else:
            return f"{node.identifier}"

    def _get_condition_identifiers(self, node):
        res = set()
        if hasattr(node, 'left'):
            res.update(self._get_condition_identifiers(node.left))
            res.update(self._get_condition_identifiers(node.right))
        else:
            res.add(node.identifier)
        return res

    def _flatten_conditions(self, node):
        nodes = []
        if hasattr(node, 'left'):
            nodes.extend(self._flatten_conditions(node.left))
            nodes.extend(self._flatten_conditions(node.right))
        else:
            nodes.append(node)
        return nodes