import sys
import os

# Ajustar el path para que reconozca la carpeta raíz
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from src.main import execute_pipeline

CASES = [
    {
        "id": "7.1 Case 1",
        "rules": "rule r1:\nif temp > 30 then alert",
        "state": "temp = 35",
        "expected_substring": "alert"
    },
    {
        "id": "7.2 Case 2",
        "rules": "rule r1:\nif temp > 30 then alert\n\nrule r2:\nif alert then fan_on",
        "state": "temp = 35",
        "expected_substring": "fan_on"
    },
    {
        "id": "7.3 Case 3",
        "rules": "rule r1:\nif temp > 30 then alert",
        "state": "temp = 20",
        "expected_substring": "" # Espera vacío o (no output)
    },
    {
        "id": "7.4 Case 4",
        "rules": "rule r1:\nif temp > 30 AND humidity < 50 then alert",
        "state": "temp = 35\nhumidity = 40",
        "expected_substring": "alert"
    },
    {
        "id": "7.5 Case 5",
        "rules": "",
        "state": "temp = 35\nhumidity = 60",
        "expected_substring": ""
    },
    {
        "id": "7.6 Case 6",
        "rules": "rule r1:\nif temp > 30 then fan_on\n\nrule r2:\nif humidity < 50 then fan_on",
        "state": "temp = 35\nhumidity = 40",
        "expected_substring": "Action fan_on generated by r1, r2"
    },
    {
        "id": "7.7 Case 7",
        "rules": "rule r1:\nif temp > 30 then alert\n\nrule r2:\nif temp > 30 then alert",
        "state": "",
        "expected_substring": "Redundant rules: r1, r2"
    },
    {
        "id": "7.8 Case 8",
        "rules": "rule r1:\nif temp > 30 then alert\n\nrule r2:\nif alert then fan_on\n\nrule r3:\nif humidity < 20 then cooling",
        "state": "temp = 25\nhumidity = 50",
        "expected_substring": "Potentially inactive rule: r3"
    },
    {
        "id": "Additional Test Case (for grading)",
        "rules": "rule r1:\nif a then b\n\nrule r2:\nif b then c\n\nrule r3:\nif c then d\n\nrule r4:\nif d then e",
        "state": "a",
        "expected_substring": "e"
    }
]

def run_all_tests():
    passed = 0
    
    for case in CASES:
        print(case["id"])
        try:
            result = execute_pipeline(case["rules"], case["state"]).strip()
            
            # Imprime la salida cruda calculada por tu motor
            if "Analysis:" in result or "Output:" in result:
                print(result)
            else:
                if result == "" or result == "(no output)":
                    print("Output:\n(no output)")
                else:
                    print(f"Output:\n{result}")
            
            # Validación interna silenciosa para el contador final
            # Verifica si la salida contiene lo esperado para asegurar que pasó
            if case["expected_substring"] in result:
                passed += 1
                
        except Exception as e:
            print(f"Error ejecutando pipeline: {e}")
        
        print() # Separación limpia entre casos
        
    # Mensaje técnico final sin decoraciones ruidosas
    print(f"Result: ({passed}/{len(CASES)} passed)")

if __name__ == "__main__":
    run_all_tests()