import sys
import os

# Ajustar el path para que reconozca la carpeta raíz
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from src.main import execute_pipeline

CASES = {
    "Caso 1: Comparación simple exitosa": {
        "rules": "rule r1:\nif temp > 30 then alert",
        "state": "temp = 35",
        "expected": "alert"
    },
    "Caso 2: Encadenamiento hacia adelante básico": {
        "rules": "rule r1:\nif temp > 30 then alert\n\nrule r2:\nif alert then fan_on",
        "state": "temp = 35",
        "expected": "alert\nfan_on"
    },
    "Caso 3: Regla no se cumple": {
        "rules": "rule r1:\nif temp > 30 then alert",
        "state": "temp = 20",
        "expected": "(no output)"
    },
    "Caso 4: Conjunción lógica AND": {
        "rules": "rule r1:\nif temp > 30 AND humidity < 50 then alert",
        "state": "temp = 35\nhumidity = 40",
        "expected": "alert"
    },
    "Caso 5: Estado sin reglas concurrentes": {
        "rules": "",
        "state": "temp = 35\nhumidity = 60",
        "expected": "(no output)"
    },
    "Caso 6: Detección estática de conflictos": {
        "rules": "rule r1:\nif temp > 30 then fan_on\n\nrule r2:\nif humidity < 50 then fan_on",
        "state": "temp = 35\nhumidity = 40",
        "expected": "fan_on\nAction fan_on generated by r1, r2"
    },
    "Caso 7: Reglas redundantes": {
        "rules": "rule r1:\nif temp > 30 then alert\n\nrule r2:\nif temp > 30 then alert",
        "state": "",
        "expected": "(no output)\nRedundant rules: r1, r2"
    },
    "Caso 8: Regla potencialmente inactiva": {
        "rules": "rule r1:\nif temp > 30 then alert\n\nrule r2:\nif alert then fan_on\n\nrule r3:\nif humidity < 20 then cooling",
        "state": "temp = 25\nhumidity = 50",
        "expected": "(no output)\nPotentially inactive rule: r3"
    },
    "Caso Adicional: Evaluación profunda en Cascada de Hechos": {
        "rules": "rule r1:\nif a then b\n\nrule r2:\nif b then c\n\nrule r3:\nif c then d\n\nrule r4:\nif d then e",
        "state": "a",
        "expected": "b\nc\nd\ne"
    }
}

def run_all_tests():
    passed = 0
    print("="*60)
    print("🕵️‍♂️ INICIANDO SUITE DE PRUEBAS AUTOMATIZADAS DEL COMPILADOR")
    print("="*60)
    
    for name, data in CASES.items():
        try:
            result = execute_pipeline(data["rules"], data["state"])
            if result.strip() == data["expected"].strip():
                print(f"✅ {name}: PASSED")
                passed += 1
            else:
                print(f"❌ {name}: FAILED")
                print(f"--- Esperado ---\n{data['expected']}")
                print(f"--- Obtenido ---\n{result}\n")
        except Exception as e:
            print(f"💥 {name}: ERROR CRÍTICO -> {e}")
            
    print("="*60)
    print(f"📊 RESULTADO FINAL: {passed}/{len(CASES)} pruebas pasadas con éxito.")
    print("="*60)

if __name__ == "__main__":
    run_all_tests()